### ISSUE TITLE
Bug: 在清屏时没有重置 article 标签的高度

### ISSUE THREAD

**Issue by Chihaya-Yuka** [Hiyoteam/hackchat-client-plus#82]
## 复现步骤

在有多条消息并且清屏后，我们会发现当键入文本时，页面会自动滚到最下方无文字区域。

## 问题描述

通过 F12 开发者工具发现 article 标签的高度没有被重置，其值为 2169.5，这不应该是一个新页面拥有的。

## 理想解决方法

在进行清屏操作时调用重置 article 的函数。

## Todo List

- [x] 我可以参与这个 issue 的贡献。 
- [ ] 实现重置 article 标签的函数。
- [ ] 在清屏时调用重置 article 标签的函数。
